version: '3.6'

services:
  web:
    build: .
    env_file: .env
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:10.3-alpine
    env_file: .env
    volumes:
      - ./db-data:/var/lib/postgresql/db-data

